
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6-slim

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - build
  - deploy

before_script:
  - python -V  # Print out python version for debugging
  - pip install tox flake8 
  - apt-get update
  - apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
  - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"

test-py36:
  stage: test
  script:
    - tox -e py36,flake8

test-py37:
  stage: test
  script:
    - pyenv install 3.7.4
    - tox -e py37,flake8

test-py38:
  stage: test
  script:
    - pyenv install 3.8-dev
    - tox -e py38,flake8

build:
  stage: build
  only:
    - tags
  script:
    - python setup.py bdist_wheel
    # an alternative approach is to install and run:
    - pip install dist/*
    # run the command here
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.whl

deploy:
  stage: deploy
  only:
    - tags
  script:
    - pip install twine
    - twine upload dist/*